# Pandas 

### Day 2

In [3]:
import pandas as pd

## read data from csv file or excel file

In [4]:
df = pd.read_csv("students.csv")

In [8]:
df

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
0,1001,Aarav,22,Male,Pune,Data Science,NaN,NaN,D,Paid
1,1002,Aditya,21,Male,Pune,Java,NaN,94.0,B,Pending
2,1003,Tanya,18,Female,Mumbai,C++,89.0,NaN,B,Pending
3,1004,Aditya,24,Male,Delhi,AI,79.0,62.0,A,Pending
4,1005,Kabir,23,Male,Patna,Data Science,NaN,74.0,A,Paid
...,...,...,...,...,...,...,...,...,...,...
95,1096,Asif,21,Male,Noida,Java,NaN,NaN,C,Paid
96,1097,Zoya,22,Female,Patna,Web Development,NaN,74.0,A,Pending
97,1098,Aditya,25,Male,Jaipur,C++,NaN,NaN,A,Pending
98,1099,Priya,19,Female,Pune,Java,52.0,89.0,D,Paid
99,1100,Sakshi,19,Female,Bhopal,Java,87.0,62.0,B,Pending

## info() of dataframe

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  100 non-null    int64
 1   Name        100 non-null    str
 2   Age         100 non-null    int64
 3   Gender      100 non-null    str
 4   City        100 non-null    str
 5   Course      100 non-null    str
 6   Marks       45 non-null     float64
 7   Attendance  49 non-null     float64
 8   Grade       100 non-null    str
 9   Fee_Status  100 non-null    str
dtypes: float64(2), int64(2), str(6)
memory usage: 10.8 KB

## describe() - used to give a description of dataframe

In [10]:
df.describe()

        Student_ID         Age       Marks  Attendance
count   100.000000  100.000000   45.000000   49.000000
mean   1050.500000   22.100000   71.022222   81.653061
std      29.011492    2.508571   15.648829   11.277838
min    1001.000000   18.000000   35.000000   60.000000
25%    1025.750000   20.000000   60.000000   74.000000
50%    1050.500000   22.000000   70.000000   82.000000
75%    1075.250000   24.000000   83.000000   90.000000
max    1100.000000   26.000000  100.000000  100.000000

## head - top 5 record

In [15]:
df.head()

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
0,1001,Aarav,22,Male,Pune,Data Science,NaN,NaN,D,Paid
1,1002,Aditya,21,Male,Pune,Java,NaN,94.0,B,Pending
2,1003,Tanya,18,Female,Mumbai,C++,89.0,NaN,B,Pending
3,1004,Aditya,24,Male,Delhi,AI,79.0,62.0,A,Pending
4,1005,Kabir,23,Male,Patna,Data Science,NaN,74.0,A,Paid

## tail - bottom 5 recods

In [13]:
df.tail()

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
95,1096,Asif,21,Male,Noida,Java,NaN,NaN,C,Paid
96,1097,Zoya,22,Female,Patna,Web Development,NaN,74.0,A,Pending
97,1098,Aditya,25,Male,Jaipur,C++,NaN,NaN,A,Pending
98,1099,Priya,19,Female,Pune,Java,52.0,89.0,D,Paid
99,1100,Sakshi,19,Female,Bhopal,Java,87.0,62.0,B,Pending

## dataframe properties
* shape
* columns
* dtypes

In [20]:
df.shape

(100, 10)

In [17]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Course', 'Marks',
       'Attendance', 'Grade', 'Fee_Status'],
      dtype='str')

In [18]:
df.dtypes

Student_ID      int64
Name              str
Age             int64
Gender            str
City              str
Course            str
Marks         float64
Attendance    float64
Grade             str
Fee_Status        str
dtype: object

## selecting rows and columns

In [21]:
# columns - single
df["Name"]

0      Aarav
1     Aditya
2      Tanya
3     Aditya
4      Kabir
       ...
95      Asif
96      Zoya
97    Aditya
98     Priya
99    Sakshi
Name: Name, Length: 100, dtype: str

In [22]:
# multiple columns
df[["Name", "Age", "Gender"]]

      Name  Age  Gender
0    Aarav   22    Male
1   Aditya   21    Male
2    Tanya   18  Female
3   Aditya   24    Male
4    Kabir   23    Male
..     ...  ...     ...
95    Asif   21    Male
96    Zoya   22  Female
97  Aditya   25    Male
98   Priya   19  Female
99  Sakshi   19  Female

[100 rows x 3 columns]

In [23]:
# rows - single
df.iloc[0]

Student_ID            1001
Name                 Aarav
Age                     22
Gender                Male
City                  Pune
Course        Data Science
Marks                  NaN
Attendance             NaN
Grade                    D
Fee_Status            Paid
Name: 0, dtype: object

In [26]:
# rows - multiple
df.iloc[0:4]

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
0,1001,Aarav,22,Male,Pune,Data Science,NaN,NaN,D,Paid
1,1002,Aditya,21,Male,Pune,Java,NaN,94.0,B,Pending
2,1003,Tanya,18,Female,Mumbai,C++,89.0,NaN,B,Pending
3,1004,Aditya,24,Male,Delhi,AI,79.0,62.0,A,Pending

## filtering

In [29]:
df[df["Marks"]>90]

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
6,1007,Rohan,26,Male,Pune,Data Science,94.0,NaN,C,Paid
35,1036,Aisha,19,Female,Jaipur,AI,100.0,94.0,A,Paid
51,1052,Arjun,24,Male,Kanpur,Data Science,93.0,81.0,C,Pending
65,1066,Aarav,22,Male,Bhopal,Web Development,91.0,NaN,C,Pending
67,1068,Deepak,21,Male,Indore,Web Development,92.0,79.0,C,Paid
76,1077,Priya,24,Female,Indore,Python,94.0,NaN,C,Pending

In [32]:
# age>25
df[df["Age"] == 26]

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
6,1007,Rohan,26,Male,Pune,Data Science,94.0,NaN,C,Paid
15,1016,Ishita,26,Female,Bhopal,Python,NaN,64.0,A,Paid
17,1018,Neha,26,Female,Mumbai,C++,NaN,90.0,B,Paid
22,1023,Meera,26,Female,Bhopal,Data Science,59.0,NaN,A,Pending
31,1032,Ritika,26,Female,Mumbai,Web Development,NaN,79.0,A,Pending
38,1039,Kabir,26,Male,Jaipur,C++,87.0,85.0,B,Paid
44,1045,Ankit,26,Male,Indore,Java,75.0,99.0,D,Paid
50,1051,Sneha,26,Female,Lucknow,Web Development,NaN,NaN,D,Paid
72,1073,Pooja,26,Female,Bhopal,Web Development,NaN,87.0,C,Paid
84,1085,Priya,26,Female,Bhopal,Python,53.0,NaN,D,Pending
94,1095,Pooja,26,Female,Jaipur,Data Science,67.0,78.0,A,Pending

In [36]:
# multiple conditions
df[(df["Marks"] > 80) & (df["Attendance"] > 80)]

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Grade,Fee_Status
35,1036,Aisha,19,Female,Jaipur,AI,100.0,94.0,A,Paid
38,1039,Kabir,26,Male,Jaipur,C++,87.0,85.0,B,Paid
51,1052,Arjun,24,Male,Kanpur,Data Science,93.0,81.0,C,Pending
61,1062,Neha,24,Female,Pune,AI,82.0,95.0,D,Pending
85,1086,Ritika,24,Female,Delhi,AI,83.0,100.0,A,Paid